name: Deploy to Heroku
env:
  HEROKU_APP_NAME: "svaliava-water-site"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pass secrets and vars to ENV
        uses: ./.github/actions/merge-json-to-env
        with:
          jsons: |
            ${{ toJSON(secrets) }}

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        uses: sstepanchuk/heroku-deploy
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: "stepanchuk.dev@gmail.com"
          usedocker: true
          env_file: ".env"
          docker_heroku_process_type: "web"